/* eslint-disable react/prop-types */
import { useEffect } from "react";
import "./styles/styles.css";
import { parallaxMouseMovement, parallaxScroll } from "@/utlis/parallax";

import { init_wow } from "@/utlis/initWowjs";
import { headerChangeOnScroll } from "@/utlis/changeHeaderOnScroll";
import { Route, Routes, useLocation } from "react-router-dom";
import PreviewPage from "@/pages/page";
import Home1MainDemoMultiPage from "@/pages/homes/home-1/main-demo/main-multi-page/page";
import Home1TypedTextMultiPage from "@/pages/homes/home-1/typed-text/main-multi-page-typed-text/page";
import Home1ImageParallaxMultiPage from "@/pages/homes/home-1/image-parallax/main-multi-page-image-parallax/page";
import Home1SliderFullscreenMultiPage from "@/pages/homes/home-1/slider-fullscreen/main-multi-page-slider-fullscreen/page";
import Home1SliderBackgroundMultiPage from "@/pages/homes/home-1/slider-background/main-multi-page-slider-background/page";
import Home1BGVideoMultiPage from "@/pages/homes/home-1/bg-video/main-multi-page-bg-video/page";
import Home1BGVideoYoutubeMultiPage from "@/pages/homes/home-1/bg-video-youtube/main-multi-page-bg-video-youtube/page";
import Home1MainDemoOnepage from "@/pages/homes/home-1/main-demo/main-one-page/page";
import Home1TypedTextOnepage from "@/pages/homes/home-1/typed-text/main-one-page-typed-text/page";
import Home1ImageParallaxOnepage from "@/pages/homes/home-1/image-parallax/main-one-page-image-parallax/page";
import Home1SliderFullscreenOnepage from "@/pages/homes/home-1/slider-fullscreen/main-one-page-slider-fullscreen/page";
import Home1SliderBackgroundOnepage from "@/pages/homes/home-1/slider-background/main-one-page-slider-background/page";
import Home1BGVideoOnepage from "@/pages/homes/home-1/bg-video/main-one-page-bg-video/page";
import Home1BGVideoYoutubeOnepage from "@/pages/homes/home-1/bg-video-youtube/main-one-page-bg-video-youtube/page";
import Home1MainDemoMultiPageDark from "@/pages/homes/home-1/main-demo/main-multi-page-dark/page";
import Home1TypedTextMultiPageDark from "@/pages/homes/home-1/typed-text/main-multi-page-typed-text-dark/page";
import Home1ImageParallaxMultiPageDark from "@/pages/homes/home-1/image-parallax/main-multi-page-image-parallax-dark/page";
import Home1SliderFullscreenMultiPageDark from "@/pages/homes/home-1/slider-fullscreen/main-multi-page-slider-fullscreen-dark/page";
import Home1SliderBackgroundMultiPageDark from "@/pages/homes/home-1/slider-background/main-multi-page-slider-background-dark/page";
import Home1BGVideoMultiPageDark from "@/pages/homes/home-1/bg-video/main-multi-page-bg-video-dark/page";
import Home1MainDemoOnepageDark from "@/pages/homes/home-1/main-demo/main-one-page-dark/page";
import Home1TypedTextOnepageDark from "@/pages/homes/home-1/typed-text/main-one-page-typed-text-dark/page";
import Home1ImageParallaxOnepageDark from "@/pages/homes/home-1/image-parallax/main-one-page-image-parallax-dark/page";
import Home1SliderFullscreenOnepageDark from "@/pages/homes/home-1/slider-fullscreen/main-one-page-slider-fullscreen-dark/page";
import Home1SliderBackgroundOnepageDark from "@/pages/homes/home-1/slider-background/main-one-page-slider-background-dark/page";
import Home1BGVideoOnepageDark from "@/pages/homes/home-1/bg-video/main-one-page-bg-video-dark/page";
import Home1BGVideoYoutubeOnepageDark from "@/pages/homes/home-1/bg-video-youtube/main-one-page-bg-video-youtube-dark/page";
import Home2MainDemoMultiPage from "@/pages/homes/home-2/main-demo/bold-multi-page/page";
import Home2TypedTextMultiPage from "@/pages/homes/home-2/typed-text/bold-multi-page-typed-text/page";
import Home2BGVideoMultiPage from "@/pages/homes/home-2/bg-video/bold-multi-page-bg-video/page";
import Home2MainDemoOnepage from "@/pages/homes/home-2/main-demo/bold-one-page/page";
import Home2TypedTextOnepage from "@/pages/homes/home-2/typed-text/bold-one-page-typed-text/page";
import Home2BGVideoOnepage from "@/pages/homes/home-2/bg-video/bold-one-page-bg-video/page";
import Home2MainDemoMultiPageDark from "@/pages/homes/home-2/main-demo/bold-multi-page-dark/page";
import Home2TypedTextMultiPageDark from "@/pages/homes/home-2/typed-text/bold-multi-page-typed-text-dark/page";
import Home2BGVideoMultiPageDark from "@/pages/homes/home-2/bg-video/bold-multi-page-bg-video-dark/page";
import Home2MainDemoOnepageDark from "@/pages/homes/home-2/main-demo/bold-one-page-dark/page";
import Home2TypedTextOnepageDark from "@/pages/homes/home-2/typed-text/bold-one-page-typed-text-dark/page";
import Home2BGVideoOnepageDark from "@/pages/homes/home-2/bg-video/bold-one-page-bg-video-dark/page";
import Home3MainDemoMultiPage from "@/pages/homes/home-3/main-demo/brutalist-multi-page/page";
import Home3BGVideoMultiPage from "@/pages/homes/home-3/bg-video/brutalist-multi-page-bg-video/page";
import Home3BGVideoYoutubeMultiPage from "@/pages/homes/home-3/bg-video-youtube/brutalist-multi-page-bg-video-youtube/page";
import Home3MainDemoOnepage from "@/pages/homes/home-3/main-demo/brutalist-one-page/page";
import Home3BGVideoOnepage from "@/pages/homes/home-3/bg-video/brutalist-one-page-bg-video/page";
import Home3BGVideoYoutubeOnepage from "@/pages/homes/home-3/bg-video-youtube/brutalist-one-page-bg-video-youtube/page";
import Home3BGVideoMultiPageDark from "@/pages/homes/home-3/bg-video/brutalist-multi-page-bg-video-dark/page";
import Home3BGVideoYoutubeMultiPageDark from "@/pages/homes/home-3/bg-video-youtube/brutalist-multi-page-bg-video-youtube-dark/page";
import Home3MainDemoOnepageDark from "@/pages/homes/home-3/main-demo/brutalist-multi-page-dark/page";
import Home3BGVideoOnepageDark from "@/pages/homes/home-3/bg-video/brutalist-one-page-bg-video-dark/page";
import Home3BGVideoYoutubeOnepageDark from "@/pages/homes/home-3/bg-video-youtube/brutalist-one-page-bg-video-youtube-dark/page";
import Home3MainDemoMultipageDark from "@/pages/homes/home-3/main-demo/brutalist-multi-page-dark/page";
import Home4MainDemoMultiPage from "@/pages/homes/home-4/main-demo/corporate-multi-page/page";
import Home4ImageParallaxMultiPage from "@/pages/homes/home-4/image-parallax/corporate-multi-page-image-parallax/page";
import Home4BGVideoMultiPage from "@/pages/homes/home-4/bg-video/corporate-multi-page-bg-video/page";
import Home4SplitMultiPage from "@/pages/homes/home-4/split/corporate-multi-page-split/page";
import Home4MainDemoOnepage from "@/pages/homes/home-4/main-demo/corporate-one-page/page";
import Home4ImageParallaxOnepage from "@/pages/homes/home-4/image-parallax/corporate-one-page-image-parallax/page";
import Home4BGVideoOnepage from "@/pages/homes/home-4/bg-video/corporate-one-page-bg-video/page";
import Home4SplitOnepage from "@/pages/homes/home-4/split/corporate-one-page-split/page";
import Home4MainDemoMultiPageDark from "@/pages/homes/home-4/main-demo/corporate-multi-page-dark/page";
import Home4ImageParallaxMultiPageDark from "@/pages/homes/home-4/image-parallax/corporate-multi-page-image-parallax-dark/page";
import Home4BGVideoMultiPageDark from "@/pages/homes/home-4/bg-video/corporate-multi-page-bg-video-dark/page";
import Home4SplitMultiPageDark from "@/pages/homes/home-4/split/corporate-multi-page-split-dark/page";
import Home4MainDemoOnepageDark from "@/pages/homes/home-4/main-demo/corporate-one-page-dark/page";
import Home4ImageParallaxOnepageDark from "@/pages/homes/home-4/image-parallax/corporate-one-page-image-parallax-dark/page";
import Home4BGVideoOnepageDark from "@/pages/homes/home-4/bg-video/corporate-one-page-bg-video-dark/page";
import Home4SplitOnepageDark from "@/pages/homes/home-4/split/corporate-one-page-split-dark/page";
import Home5MainDemoMultiPage from "@/pages/homes/home-5/main-demo/elegant-multi-page/page";
import Home5BGVideoMultiPage from "@/pages/homes/home-5/bg-video/elegant-multi-page-bg-video/page";
import Home5SplitMultiPage from "@/pages/homes/home-5/split/elegant-multi-page-split/page";
import Home5MainDemoOnepage from "@/pages/homes/home-5/main-demo/elegant-one-page/page";
import Home5BGVideoOnepage from "@/pages/homes/home-5/bg-video/elegant-one-page-bg-video/page";
import Home5SplitOnepage from "@/pages/homes/home-5/split/elegant-one-page-split/page";
import Home5MainDemoMultiPageDark from "@/pages/homes/home-5/main-demo/elegant-multi-page-dark/page";
import Home5BGVideoMultiPageDark from "@/pages/homes/home-5/bg-video/elegant-multi-page-bg-video-dark/page";
import Home5SplitMultiPageDark from "@/pages/homes/home-5/split/elegant-multi-page-split-dark/page";
import Home5MainDemoOnepageDark from "@/pages/homes/home-5/main-demo/elegant-one-page-dark/page";
import Home5BGVideoOnepageDark from "@/pages/homes/home-5/bg-video/elegant-one-page-bg-video-dark/page";
import Home5SplitOnepageDark from "@/pages/homes/home-5/split/elegant-one-page-split-dark/page";
import Home6MainDemoMultiPage from "@/pages/homes/home-6/main-demo/fancy-multi-page/page";
import Home6ImageParallaxMultiPage from "@/pages/homes/home-6/image-parallax/fancy-multi-page-image-parallax/page";
import Home6BGVideoMultiPage from "@/pages/homes/home-6/bg-video/fancy-multi-page-bg-video/page";
import Home6MainDemoOnepage from "@/pages/homes/home-6/main-demo/fancy-one-page/page";
import Home6ImageParallaxOnepage from "@/pages/homes/home-6/image-parallax/fancy-one-page-image-parallax/page";
import Home6BGVideoOnepage from "@/pages/homes/home-6/bg-video/fancy-one-page-bg-video/page";
import Home6MainDemoMultiPageDark from "@/pages/homes/home-6/main-demo/fancy-multi-page-dark/page";
import Home6ImageParallaxMultiPageDark from "@/pages/homes/home-6/image-parallax/fancy-multi-page-image-parallax-dark/page";
import Home6BGVideoMultiPageDark from "@/pages/homes/home-6/bg-video/fancy-multi-page-bg-video-dark/page";
import Home6MainDemoOnepageDark from "@/pages/homes/home-6/main-demo/fancy-one-page-dark/page";
import Home6ImageParallaxOnepageDark from "@/pages/homes/home-6/image-parallax/fancy-one-page-image-parallax-dark/page";
import Home6BGVideoOnepageDark from "@/pages/homes/home-6/bg-video/fancy-one-page-bg-video-dark/page";
import Home7MainDemoMultiPage from "@/pages/homes/home-7/main-demo/gradient-multi-page/page";
import Home7ImageParallax1MultiPage from "@/pages/homes/home-7/image-parallax-1/gradient-multi-page-image-parallax-1/page";
import Home7ImageParallax2MultiPage from "@/pages/homes/home-7/image-parallax-2/gradient-multi-page-image-parallax-2/page";
import Home7BGVideoMultiPage from "@/pages/homes/home-7/bg-video/gradient-multi-page-bg-video/page";
import Home7MainDemoOnepage from "@/pages/homes/home-7/main-demo/gradient-one-page/page";
import Home7ImageParallax1Onepage from "@/pages/homes/home-7/image-parallax-1/gradient-one-page-image-parallax-1/page";
import Home7ImageParallax2Onepage from "@/pages/homes/home-7/image-parallax-2/gradient-one-page-image-parallax-2/page";
import Home7BGVideoOnepage from "@/pages/homes/home-7/bg-video/gradient-one-page-bg-video/page";
import Home7MainDemoMultiPageDark from "@/pages/homes/home-7/main-demo/gradient-multi-page-dark/page";
import Home7ImageParallax1MultiPageDark from "@/pages/homes/home-7/image-parallax-1/gradient-multi-page-image-parallax-1-dark/page";
import Home7ImageParallax2MultiPageDark from "@/pages/homes/home-7/image-parallax-2/gradient-multi-page-image-parallax-2-dark/page";
import Home7BGVideoMultiPageDark from "@/pages/homes/home-7/bg-video/gradient-multi-page-bg-video-dark/page";
import Home7MainDemoOnepageDark from "@/pages/homes/home-7/main-demo/gradient-one-page-dark/page";
import Home7ImageParallax1OnepageDark from "@/pages/homes/home-7/image-parallax-1/gradient-one-page-image-parallax-1-dark/page";
import Home7ImageParallax2OnepageDark from "@/pages/homes/home-7/image-parallax-2/gradient-one-page-image-parallax-2-dark/page";
import Home7BGVideoOnepageDark from "@/pages/homes/home-7/bg-video/gradient-one-page-bg-video-dark/page";
import Home8MainDemoMultiPage from "@/pages/homes/home-8/main-demo/modern-multi-page/page";
import Home8ImageParallax1MultiPage from "@/pages/homes/home-8/image-parallax-1/modern-multi-page-image-parallax-1/page";
import Home8ImageParallax2MultiPage from "@/pages/homes/home-8/image-parallax-2/modern-multi-page-image-parallax-2/page";
import Home8TypedTextMultiPage from "@/pages/homes/home-8/typed-text/modern-multi-page-typed-text/page";
import Home8BGVideoMultiPage from "@/pages/homes/home-8/bg-video/modern-multi-page-bg-video/page";
import Home8MainDemoOnepage from "@/pages/homes/home-8/main-demo/modern-one-page/page";
import Home8ImageParallax1Onepage from "@/pages/homes/home-8/image-parallax-1/modern-one-page-image-parallax-1/page";
import Home8ImageParallax2Onepage from "@/pages/homes/home-8/image-parallax-2/modern-one-page-image-parallax-2/page";
import Home8TypedTextOnepage from "@/pages/homes/home-8/typed-text/modern-one-page-typed-text/page";
import Home8BGVideoOnepage from "@/pages/homes/home-8/bg-video/modern-one-page-bg-video/page";
import Home8MainDemoMultiPageDark from "@/pages/homes/home-8/main-demo/modern-multi-page-dark/page";
import Home8ImageParallax1MultiPageDark from "@/pages/homes/home-8/image-parallax-1/modern-multi-page-image-parallax-1-dark/page";
import Home8ImageParallax2MultiPageDark from "@/pages/homes/home-8/image-parallax-2/modern-multi-page-image-parallax-2-dark/page";
import Home8TypedTextMultiPageDark from "@/pages/homes/home-8/typed-text/modern-multi-page-typed-text-dark/page";
import Home8BGVideoMultiPageDark from "@/pages/homes/home-8/bg-video/modern-multi-page-bg-video-dark/page";
import Home8MainDemoOnepageDark from "@/pages/homes/home-8/main-demo/modern-one-page-dark/page";
import Home8ImageParallax1OnepageDark from "@/pages/homes/home-8/image-parallax-1/modern-one-page-image-parallax-1-dark/page";
import Home8ImageParallax2OnepageDark from "@/pages/homes/home-8/image-parallax-2/modern-one-page-image-parallax-2-dark/page";
import Home8TypedTextOnepageDark from "@/pages/homes/home-8/typed-text/modern-one-page-typed-text-dark/page";
import Home8BGVideoOnepageDark from "@/pages/homes/home-8/bg-video/modern-one-page-bg-video-dark/page";
import Home9MainDemoMultiPage from "@/pages/homes/home-9/main-demo/slick-multi-page/page";
import Home9SplitMultiPage from "@/pages/homes/home-9/split/slick-multi-page-split/page";
import Home9MainDemoOnepage from "@/pages/homes/home-9/main-demo/slick-one-page/page";
import Home9SplitOnepage from "@/pages/homes/home-9/split/slick-one-page-split/page";
import Home9MainDemoOnepageDark from "@/pages/homes/home-9/main-demo/slick-one-page-dark/page";
import Home9SplitOnepageDark from "@/pages/homes/home-9/split/slick-one-page-split-dark/page";
import Home10MainDemoMultiPage from "@/pages/homes/home-10/main-deno/strong-multi-page/page";
import Home10ImageParallaxMultiPage from "@/pages/homes/home-10/image-parallax/strong-multi-page-image-parallax/page";
import Home10BGVideoMultiPage from "@/pages/homes/home-10/bg-video/strong-multi-page-bg-video/page";
import Home10MainDemoOnepage from "@/pages/homes/home-10/main-deno/strong-one-page/page";
import Home10ImageParallaxOnepage from "@/pages/homes/home-10/image-parallax/strong-one-page-image-parallax/page";
import Home10BGVideoOnepage from "@/pages/homes/home-10/bg-video/strong-one-page-bg-video/page";
import Home10MainDemoMultiPageDark from "@/pages/homes/home-10/main-deno/strong-multi-page-dark/page";
import Home10ImageParallaxMultiPageDark from "@/pages/homes/home-10/image-parallax/strong-multi-page-image-parallax-dark/page";
import Home10BGVideoMultiPageDark from "@/pages/homes/home-10/bg-video/strong-multi-page-bg-video-dark/page";
import Home10MainDemoOnepageDark from "@/pages/homes/home-10/main-deno/strong-one-page-dark/page";
import Home10ImageParallaxOnepageDark from "@/pages/homes/home-10/image-parallax/strong-one-page-image-parallax-dark/page";
import Home10BGVideoOnepageDark from "@/pages/homes/home-10/bg-video/strong-one-page-bg-video-dark/page";
import MainPortfolioPageBoxed2Col from "./pages/portfolio/main-portfolio-boxed-2col/page";
import MainPortfolioPageBoxed3Col from "./pages/portfolio/main-portfolio-boxed-3col/page";
import MainPortfolioPageBoxed4Col from "./pages/portfolio/main-portfolio-boxed-4col/page";
import MainPortfolioPageWide2Col from "./pages/portfolio/main-portfolio-wide-2col/page";
import MainPortfolioPageWide3Col from "./pages/portfolio/main-portfolio-wide-3col/page";
import MainPortfolioPageWide4Col from "./pages/portfolio/main-portfolio-wide-4col/page";
import MainPortfolioPageMasonry2Col from "./pages/portfolio/main-portfolio-masonry-2col/page";
import MainPortfolioPageMasonry3Col from "./pages/portfolio/main-portfolio-masonry-3col/page";
import MainPortfolioPageMasonry4Col from "./pages/portfolio/main-portfolio-masonry-4col/page";
import MainPortfolioSinglePage1 from "./pages/portfolio-single/main-portfolio-single-1/page";
import MainPortfolioSinglePage2 from "./pages/portfolio-single/main-portfolio-single-2/page";
import MainPortfolioSinglePage3 from "./pages/portfolio-single/main-portfolio-single-3/page";
import MainPortfolioPageLazyload from "./pages/portfolio/main-portfolio-lazyload/page";
import MainPortfolioPageBoxed2ColDark from "./pages/portfolio/main-portfolio-boxed-2col-dark/page";
import MainPortfolioPageBoxed3ColDark from "./pages/portfolio/main-portfolio-boxed-3col-dark/page";
import MainPortfolioPageBoxed4ColDark from "./pages/portfolio/main-portfolio-boxed-4col-dark/page";
import MainPortfolioPageWide2ColDark from "./pages/portfolio/main-portfolio-wide-2col-dark/page";
import MainPortfolioPageWide3ColDark from "./pages/portfolio/main-portfolio-wide-3col-dark/page";
import MainPortfolioPageWide4ColDark from "./pages/portfolio/main-portfolio-wide-4col-dark/page";
import MainPortfolioPageLazyloadDark from "./pages/portfolio/main-portfolio-lazyload-dark/page";
import MainPortfolioPageMasonry2ColDark from "./pages/portfolio/main-portfolio-masonry-2col-dark/page";
import MainPortfolioPageMasonry3ColDark from "./pages/portfolio/main-portfolio-masonry-3col-dark/page";
import MainPortfolioPageMasonry4ColDark from "./pages/portfolio/main-portfolio-masonry-4col-dark/page";
import MainPortfolioSinglePage1Dark from "./pages/portfolio-single/main-portfolio-single-1-dark/page";
import MainPortfolioSinglePage2Dark from "./pages/portfolio-single/main-portfolio-single-2-dark/page";
import MainPortfolioSinglePage3Dark from "./pages/portfolio-single/main-portfolio-single-3-dark/page";
import MainBlogClassicPageSidebarLeft from "./pages/blogs/main-blog-classic-sidebar-left/page";
import MainBlogClassicPageSidebarRight from "./pages/blogs/main-blog-classic-sidebar-right/page";
import MainBlogClassicPageFullWidth from "./pages/blogs/main-blog-classic-fullwidth/page";
import MainBlogColumnsPage2Col from "./pages/blogs/main-blog-columns-2col/page";
import MainBlogColumnsPage3Col from "./pages/blogs/main-blog-columns-3col/page";
import MainBlogSinglePageSIdebarLeft from "./pages/blog-single/main-blog-single-sidebar-left/page";
import MainBlogSinglePageSidebarRight from "./pages/blog-single/main-blog-single-sidebar-right/page";
import MainBlogSinglePageFullWidth from "./pages/blog-single/main-blog-single-fullwidth/page";
import MainBlogClassicPageSidebarLeftDark from "./pages/blogs/main-blog-classic-sidebar-left-dark/page";
import MainBlogClassicPageSidebarRightDark from "./pages/blogs/main-blog-classic-sidebar-right-dark/page";
import MainBlogClassicPageFullWidthDark from "./pages/blogs/main-blog-classic-fullwidth-dark/page";
import MainBlogColumnsPage2ColDark from "./pages/blogs/main-blog-columns-2col-dark/page";
import MainBlogColumnsPage3ColDark from "./pages/blogs/main-blog-columns-3col-dark/page";
import MainBlogSinglePageSIdebarLeftDark from "./pages/blog-single/main-blog-single-sidebar-left-dark/page";
import MainBlogSinglePageSidebarRightDark from "./pages/blog-single/main-blog-single-sidebar-right-dark/page";
import MainBlogSinglePageFullWidthDark from "./pages/blog-single/main-blog-single-fullwidth-dark/page";
import ElementPageAccordion from "./pages/elements/main-elements-accordions/page";
import ElementPageAlertMessage from "./pages/elements/main-elements-alert-messages/page";
import ElementPageAnimation from "./pages/elements/main-elements-animation/page";
import ElementPageBars from "./pages/elements/main-elements-bars/page";
import ElementPageButtons from "./pages/elements/main-elements-buttons/page";
import ElementPageCookieBanner from "./pages/elements/main-elements-cookie-banner/page";
import ElementPageFeatures from "./pages/elements/main-elements-features/page";
import ElementPageForms from "./pages/elements/main-elements-forms/page";
import ElementPageGrid from "./pages/elements/main-elements-grid/page";
import ElementPageIconsBrands from "./pages/elements/main-elements-icons-brands/page";
import ElementPageIconIconmonstr from "./pages/elements/main-elements-icons-iconmonstr/page";
import ElementPageIconsLonicons from "./pages/elements/main-elements-icons-Ionicons/page";
import ElementPageIconsMonicons from "./pages/elements/main-elements-icons-monoicons/page";
import ElementPageImageLazyLoad from "./pages/elements/main-elements-images-lazyload/page";
import ElementPageLightbox from "./pages/elements/main-elements-lightbox/page";
import ElementPageSlider from "./pages/elements/main-elements-sliders/page";
import ElementPageSliderLazyload from "./pages/elements/main-elements-sliders-lazyload/page";
import ElementPageTabs from "./pages/elements/main-elements-tabs/page";
import ElementPageTooltips from "./pages/elements/main-elements-tooltips/page";
import ElementPageTypography from "./pages/elements/main-elements-typography/page";
import ElementPageVideoSound from "./pages/elements/main-elements-video-sound/page";
import ElementPageAccordionDark from "./pages/elements/main-elements-accordions-dark/page";
import ElementPageAlertMessageDark from "./pages/elements/main-elements-alert-messages-dark/page";
import ElementPageAnimationDark from "./pages/elements/main-elements-animation-dark/page";
import ElementPageBarsDark from "./pages/elements/main-elements-bars-dark/page";
import ElementPageButtonsDark from "./pages/elements/main-elements-buttons-dark/page";
import ElementPageCookieBannerDark from "./pages/elements/main-elements-cookie-banner-dark/page";
import ElementPageFeaturesDark from "./pages/elements/main-elements-features-dark/page";
import ElementPageFormsDark from "./pages/elements/main-elements-forms-dark/page";
import ElementPageGridDark from "./pages/elements/main-elements-grid-dark/page";
import ElementPageIconsBrandsDark from "./pages/elements/main-elements-icons-brands-dark/page";
import ElementPageIconIconmonstrDark from "./pages/elements/main-elements-icons-iconmonstr-dark/page";
import ElementPageIconsLoniconsDark from "./pages/elements/main-elements-icons-Ionicons-dark/page";
import ElementPageIconsMoniconsDark from "./pages/elements/main-elements-icons-monoicons-dark/page";
import ElementPageImageLazyLoadDark from "./pages/elements/main-elements-images-lazyload-dark/page";
import ElementPageLightboxDark from "./pages/elements/main-elements-lightbox-dark/page";
import ElementPageSliderDark from "./pages/elements/main-elements-sliders-dark/page";
import ElementPageSliderLazyloadDark from "./pages/elements/main-elements-sliders-lazyload-dark/page";
import ElementPageTabsDark from "./pages/elements/main-elements-tabs-dark/page";
import ElementPageTooltipsDark from "./pages/elements/main-elements-tooltips-dark/page";
import ElementPageTypographyDark from "./pages/elements/main-elements-typography-dark/page";
import ElementPageVideoSoundDark from "./pages/elements/main-elements-video-sound-dark/page";
import MainPageAbout1 from "./pages/about/main-pages-about-1/page";
import MainAboutPage2 from "./pages/about/main-pages-about-2/page";
import MainAboutPage3 from "./pages/about/main-pages-about-3/page";
import MainServicesPage1 from "./pages/services/main-pages-services-1/page";
import MainServicesPage2 from "./pages/services/main-pages-services-2/page";
import MainServicesPage3 from "./pages/services/main-pages-services-3/page";
import MainPageClients from "./pages/otherPages/main-pages-clients/page";
import MainPageTeam from "./pages/otherPages/main-pages-team/page";
import MainPageFaq1 from "./pages/otherPages/main-pages-faq-1/page";
import MainPageFaq2 from "./pages/otherPages/main-pages-faq-2/page";
import MainPagePricing1 from "./pages/otherPages/main-pages-pricing-1/page";
import MainPagePricing2 from "./pages/otherPages/main-pages-pricing-2/page";
import MainPageContact1 from "./pages/otherPages/main-pages-contact-1/page";
import MainPageContact2 from "./pages/otherPages/main-pages-contact-2/page";
import MainPageGalleryCol1 from "./pages/otherPages/main-pages-gallery-1col/page";
import MainPageGalleryCol2 from "./pages/otherPages/main-pages-gallery-2col/page";
import MainPageGalleryCol3 from "./pages/otherPages/main-pages-gallery-3col/page";
import MainPageGalleryCol4 from "./pages/otherPages/main-pages-gallery-4col/page";
import MainPageUnderConstraction from "./pages/otherPages/main-pages-under-construction/page";
import MainPageAccount from "./pages/otherPages/main-pages-account/page";
import MainPageNotFound from "./pages/otherPages/main-pages-404/page";
import MainPageAbout1Dark from "./pages/about/main-pages-about-1-dark/page";
import MainAboutPage2Dark from "./pages/about/main-pages-about-2-dark/page";
import MainAboutPage3Dark from "./pages/about/main-pages-about-3-dark/page";
import MainServicesPage1Dark from "./pages/services/main-pages-services-1-dark/page";
import MainServicesPage2Dark from "./pages/services/main-pages-services-2-dark/page";
import MainServicesPage3Dark from "./pages/services/main-pages-services-3-dark/page";
import MainPageClientDark from "./pages/otherPages/main-pages-clients-dark/page";
import MainPageTeamDark from "./pages/otherPages/main-pages-team-dark/page";
import MainPageFaq1Dark from "./pages/otherPages/main-pages-faq-1-dark/page";
import MainPageFaq2Dark from "./pages/otherPages/main-pages-faq-2-dark/page";
import MainPagePricing1Dark from "./pages/otherPages/main-pages-pricing-1-dark/page";
import MainPagePricing2Dark from "./pages/otherPages/main-pages-pricing-2-dark/page";
import MainPageContact1Dark from "./pages/otherPages/main-pages-contact-1-dark/page";
import MainPageContact2Dark from "./pages/otherPages/main-pages-contact-2-dark/page";
import MainPageGalleryCol1Dark from "./pages/otherPages/main-pages-gallery-1col-dark/page";
import MainPageGalleryCol2Dark from "./pages/otherPages/main-pages-gallery-2col-dark/page";
import MainPageGalleryCol3Dark from "./pages/otherPages/main-pages-gallery-3col-dark/page";
import MainPageGalleryCol4Dark from "./pages/otherPages/main-pages-gallery-4col-dark/page";
import MainPageAccountDark from "./pages/otherPages/main-pages-account-dark/page";
import BoldAboutPage from "./pages/about/bold-about/page";
import BoldServicesPage from "./pages/services/bold-services/page";
import BoldPortfolioPage from "./pages/portfolio/bold-portfolio/page";
import BoldBlogPage from "./pages/blogs/bold-blog/page";
import BoldContactPage from "./pages/contact/bold-contact/page";
import BoldPortfolioSinglePage from "./pages/portfolio-single/bold-portfolio-single/page";
import BoldBlogSinglePage from "./pages/blog-single/bold-blog-single/page";
import BoldAboutPageDark from "./pages/about/bold-about-dark/page";
import BoldServicesPageDark from "./pages/services/bold-services-dark/page";
import BoldPortfolioPageDark from "./pages/portfolio/bold-portfolio-dark/page";
import BoldPortfolioSinglePageDark from "./pages/portfolio-single/bold-portfolio-single-dark/page";
import BoldBlogPageDark from "./pages/blogs/bold-blog-dark/page";
import BoldBlogSinglePageDark from "./pages/blog-single/bold-blog-single-dark/page";
import BoldContactPageDark from "./pages/contact/bold-contact-dark/page";
import BrutalistAboutPage from "./pages/about/brutalist-about/page";
import BrutalistServicesPage from "./pages/services/brutalist-services/page";
import BrutalistPortfolioSinglePage from "./pages/portfolio-single/brutalist-portfolio-single/page";
import BrutalistPortfolioPage from "./pages/portfolio/brutalist-portfolio/page";
import BrutalistBlogPage from "./pages/blogs/brutalist-blog/page";
import BrutalistBlogSinglePage from "./pages/blog-single/brutalist-blog-single/page";
import BrutalistContactPage from "./pages/contact/brutalist-contact/page";
import BrutalistAboutPageDark from "./pages/about/brutalist-about-dark/page";
import BrutalistServicesPageDark from "./pages/services/brutalist-services-dark/page";
import BrutalistPortfolioPageDark from "./pages/portfolio/brutalist-portfolio-dark/page";
import BrutalistPortfolioSinglePageDark from "./pages/portfolio-single/brutalist-portfolio-single-dark/page";
import BrutalistBlogPageDark from "./pages/blogs/brutalist-blog-dark/page";
import BrutalistBlogSinglePageDark from "./pages/blog-single/brutalist-blog-single-dark/page";
import BrutalistContactPageDark from "./pages/contact/brutalist-contact-dark/page";
import CorporateAboutPage from "./pages/about/corporate-about/page";
import CorporateServicesPage from "./pages/services/corporate-services/page";
import CorporatePortfolioPage from "./pages/portfolio/corporate-portfolio/page";
import CorporateBlogPage from "./pages/blogs/corporate-blog/page";
import CorporatePortfolioSinglePage from "./pages/portfolio-single/corporate-portfolio-single/page";
import CorporateBlogSinglePage from "./pages/blog-single/corporate-blog-single/page";
import CorporateContactPage from "./pages/contact/corporate-contact/page";
import CorporateAboutPageDark from "./pages/about/corporate-about-dark/page";
import CorporateServicesPageDark from "./pages/services/corporate-services-dark/page";
import CorporatePortfolioPageDark from "./pages/portfolio/corporate-portfolio-dark/page";
import CorporateBlogPageDark from "./pages/blogs/corporate-blog-dark/page";
import CorporatePortfolioSinglePageDark from "./pages/portfolio-single/corporate-portfolio-single-dark/page";
import CorporateBlogSinglePageDark from "./pages/blog-single/corporate-blog-single-dark/page";
import CorporateContactPageDark from "./pages/contact/corporate-contact-dark/page";
import ElegantAboutPage from "./pages/about/elegant-about/page";
import ElegantServicesPage from "./pages/services/elegant-services/page";
import ElegantPortfolioPage from "./pages/portfolio/elegant-portfolio/page";
import ElegantBlogPage from "./pages/blogs/elegant-blog/page";
import ElegantPortfolioSinglePage from "./pages/portfolio-single/elegant-portfolio-single/page";
import ElegantBlogSinglePage from "./pages/blog-single/elegant-blog-single/page";
import ElegantContactPage from "./pages/contact/elegant-contact/page";
import ElegantAboutPageDark from "./pages/about/elegant-about-dark/page";
import ElegantServicesPageDark from "./pages/services/elegant-services-dark/page";
import ElegantPortfolioPageDark from "./pages/portfolio/elegant-portfolio-dark/page";
import ElegantBlogPageDark from "./pages/blogs/elegant-blog-dark/page";
import ElegantPortfolioSinglePageDark from "./pages/portfolio-single/elegant-portfolio-single-dark/page";
import ElegantBlogSinglePageDark from "./pages/blog-single/elegant-blog-single-dark/page";
import ElegantContactPageDark from "./pages/contact/elegant-contact-dark/page";
import FancyAboutPage from "./pages/about/fancy-about/page";
import FancyServicesPage from "./pages/services/fancy-services/page";
import FancyPortfolioPage from "./pages/portfolio/fancy-portfolio/page";
import FancyBlogPage from "./pages/blogs/fancy-blog/page";
import FancyPortfolioSinglePage from "./pages/portfolio-single/fancy-portfolio-single/page";
import FancyBlogSinglePage from "./pages/blog-single/fancy-blog-single/page";
import FancyContactPage from "./pages/contact/fancy-contact/page";
import FancyAboutPageDark from "./pages/about/fancy-about-dark/page";
import FancyServicesPageDark from "./pages/services/fancy-services-dark/page";
import FancyPortfolioPageDark from "./pages/portfolio/fancy-portfolio-dark/page";
import FancyBlogPageDark from "./pages/blogs/fancy-blog-dark/page";
import FancyPortfolioSinglePageDark from "./pages/portfolio-single/fancy-portfolio-single-dark/page";
import FancyBlogSinglePageDark from "./pages/blog-single/fancy-blog-single-dark/page";
import FancyContactPageDark from "./pages/contact/fancy-contact-dark/page";
import GradientAboutPage from "./pages/about/gradient-about/page";
import GradientServicesPage from "./pages/services/gradient-services/page";
import GradientPortfolioPage from "./pages/portfolio/gradient-portfolio/page";
import GradientBlogPage from "./pages/blogs/gradient-blog/page";
import GradientPortfolioSinglePage from "./pages/portfolio-single/gradient-portfolio-single/page";
import GradientBlogSinglePage from "./pages/blog-single/gradient-blog-single/page";
import GradientContactPage from "./pages/contact/gradient-contact/page";
import GradientAboutPageDark from "./pages/about/gradient-about-dark/page";
import GradientServicesPageDark from "./pages/services/gradient-services-dark/page";
import GradientPortfolioPageDark from "./pages/portfolio/gradient-portfolio-dark/page";
import GradientBlogPageDark from "./pages/blogs/gradient-blog-dark/page";
import GradientPortfolioSinglePageDark from "./pages/portfolio-single/gradient-portfolio-single-dark/page";
import GradientBlogSinglePageDark from "./pages/blog-single/gradient-blog-single-dark/page";
import GradientContactPageDark from "./pages/contact/gradient-contact-dark/page";
import ModernAboutPage from "./pages/about/modern-about/page";
import ModernServicesPage from "./pages/services/modern-services/page";
import ModernPortfolioPage from "./pages/portfolio/modern-portfolio/page";
import ModernBlogPage from "./pages/blogs/modern-blog/page";
import ModernPortfolioSinglePage from "./pages/portfolio-single/modern-portfolio-single/page";
import ModernBlogSinglePage from "./pages/blog-single/modern-blog-single/page";
import ModernContactPage from "./pages/contact/modern-contact/page";
import SlickAboutPage from "./pages/about/slick-about/page";
import SlickServicesPage from "./pages/services/slick-services/page";
import SlickPortfolioPage from "./pages/portfolio/slick-portfolio/page";
import SlickBlogPage from "./pages/blogs/slick-blog/page";
import SlickPortfolioSinglePage from "./pages/portfolio-single/slick-portfolio-single/page";
import SlickBlogSinglePage from "./pages/blog-single/slick-blog-single/page";
import SlickContactPage from "./pages/contact/slick-contact/page";
import SlickAboutPageDark from "./pages/about/slick-about-dark/page";
import SlickServicesPageDark from "./pages/services/slick-services-dark/page";
import SlickPortfolioPageDark from "./pages/portfolio/slick-portfolio-dark/page";
import SlickBlogPageDark from "./pages/blogs/slick-blog-dark/page";
import SlickPortfolioSinglePageDark from "./pages/portfolio-single/slick-portfolio-single-dark/page";
import SlickBlogSinglePageDark from "./pages/blog-single/slick-blog-single-dark/page";
import SlickContactPageDark from "./pages/contact/slick-contact-dark/page";
import StrongAboutPage from "./pages/about/strong-about/page";
import StrongServicesPage from "./pages/services/strong-services/page";
import StrongPortfolioPage from "./pages/portfolio/strong-portfolio/page";
import StrongBlogPage from "./pages/blogs/strong-blog/page";
import StrongPortfolioSinglePage from "./pages/portfolio-single/strong-portfolio-single/page";
import StrongBlogSinglePage from "./pages/blog-single/strong-blog-single/page";
import StrongContactPage from "./pages/contact/strong-contact/page";
import StrongAboutPageDark from "./pages/about/strong-about-dark/page";
import StrongServicesPageDark from "./pages/services/strong-services-dark/page";
import StrongPortfolioPageDark from "./pages/portfolio/strong-portfolio-dark/page";
import StrongBlogPageDark from "./pages/blogs/strong-blog-dark/page";
import StrongPortfolioSinglePageDark from "./pages/portfolio-single/strong-portfolio-single-dark/page";
import StrongBlogSinglePageDark from "./pages/blog-single/strong-blog-single-dark/page";
import StrongContactPageDark from "./pages/contact/strong-contact-dark/page";
import ElementPageHeaderDarkLight from "./pages/elements/main-elements-header-dark-light/page";
import ElementPageHeaderDarkTransparent from "./pages/elements/main-elements-header-dark-transparent/page";
import ElementPageHeaderWhite from "./pages/elements/main-elements-header-white/page";
import ElementPageHeaderWhiteAfterScroll from "./pages/elements/main-elements-header-white-after-scroll/page";
import ElementPageHeaderWhiteTransparent from "./pages/elements/main-elements-header-white-transparent/page";
import ElementPageHeaderDarkTransparentDark from "./pages/elements/main-elements-header-dark-transparent-dark/page";
import ElementPageHeaderWhiteAfterScrollDark from "./pages/elements/main-elements-header-white-after-scroll-dark/page";
import ElementPageHeaderDarkDark from "./pages/elements/main-elements-header-dark/page";
import ScrollTopBehaviour from "./components/common/ScrollTopBehaviour";

function App() {
  const { pathname } = useLocation();
  useEffect(() => {
    init_wow();
    parallaxMouseMovement();
    var mainNav = document.querySelector(".main-nav");
    if (mainNav?.classList.contains("transparent")) {
      mainNav.classList.add("js-transparent");
    } else if (!mainNav?.classList?.contains("dark")) {
      mainNav?.classList.add("js-no-transparent-white");
    }

    window.addEventListener("scroll", headerChangeOnScroll);
    parallaxScroll();
    return () => {
      window.removeEventListener("scroll", headerChangeOnScroll);
    };
  }, [pathname]);
  useEffect(() => {
    if (typeof window !== "undefined") {
      // Import the script only on the client side
      import("bootstrap/dist/js/bootstrap.esm").then(() => {
        // Module is imported, you can access any exported functionality if
      });
    }
  }, []);
  return (
    <>
      <Routes>
        <Route path="/">
          <Route index element={<Home1MainDemoOnepage />} />
        </Route>
        {/* brutalist others page */}
        <Route path="*" element={<MainPageNotFound />} />
      </Routes>
      <ScrollTopBehaviour />
    </>
  );
}

export default App;
